### ISSUE TITLE
website in not responsive

### ISSUE THREAD

**Issue by adisuyash** [adisuyash/odin-indian-recipes#1]
### Description of the issue
The website is not responsive which means that some of the content of website blews away to anywhere when we open the website in our other devices (screenshots attached below)

### Screenshots
![image](https://github.com/adisuyash/odin-indian-recipes/assets/116362593/6286b1f3-ce6e-4d13-9b65-fee0e67cbd8a)
![image](https://github.com/adisuyash/odin-indian-recipes/assets/116362593/87e1cb6c-02b9-4b42-b32f-7a197a83a133)

**Comment by sohaibaumer** [comment]
Hi! I will do it, please assign.

**Comment by adisuyash** [comment]
> Hi! I will do it, please assign.

@sohaibaumer assigned this issue to you 🎉

**Comment by adisuyash** [comment]
Make sure to fork the project first, create a new branch and then start resolving the issue
